"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var OffscreenCanvasMesssageType;
(function (OffscreenCanvasMesssageType) {
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["create"] = 0] = "create";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["resize"] = 1] = "resize";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["expendedAll"] = 2] = "expendedAll";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["collapseAll"] = 3] = "collapseAll";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["setGroupBy"] = 4] = "setGroupBy";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["scroll"] = 10] = "scroll";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["mouseDown"] = 20] = "mouseDown";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["mouseMove"] = 21] = "mouseMove";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["mouseUp"] = 22] = "mouseUp";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["mouseLeave"] = 23] = "mouseLeave";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["mouseMoveExtended"] = 24] = "mouseMoveExtended";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["mouseUpExtended"] = 25] = "mouseUpExtended";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["TouchStart"] = 30] = "TouchStart";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["TouchMove"] = 31] = "TouchMove";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["TouchEnd"] = 32] = "TouchEnd";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["keyDown"] = 40] = "keyDown";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["askForExtentedMouseMoveAndMaouseUp"] = 100] = "askForExtentedMouseMoveAndMaouseUp";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["askForNormalMouseMoveAndMaouseUp"] = 101] = "askForNormalMouseMoveAndMaouseUp";
    OffscreenCanvasMesssageType[OffscreenCanvasMesssageType["setCursor"] = 102] = "setCursor";
})(OffscreenCanvasMesssageType = exports.OffscreenCanvasMesssageType || (exports.OffscreenCanvasMesssageType = {}));
